analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.387555
  lightness: 0.922433
  rhythmicContrast: 0.288119
  saturation: 1
cta: {}
layout_spectrum: 0.78404
name: Leia of Rage
opengraph: {}
purpose: {}
typography_spectrum: 0.343191
