layout_spectrum: 0.8818521187640727
typography_spectrum: 0.04706064146012068
color:
  brandColors:
    - '#FFFFFF'
    - '#27DA00'
    - '#0275FE'
    - '#FE1EAA'
    - '#7900FD'
  brandStrength: 0.7849463
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.2329749
coverPrefs:
  filter: false
name: Swiss Army Chick
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose: {}
title: Newer Than Ever
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
