name: Swiss Army Chick
layout_spectrum: 0.3369175
typography_spectrum: 0
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#27DA00'
    - '#0275FE'
    - '#FE1EAA'
    - '#7900FD'
  brandStrength: 0.7849463
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.2329749
purpose: {}
title: Newer Than Ever
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
