name: Leia of Rage
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 0.4784946
  brandStrength: 0.4659498
  lightness: 1
  brandColors:
    - '#65CE00'
    - '#FFFFFF'
    - '#01C3FF'
    - '#FF34E8'
    - '#326600'
  rhythmicContrast: 0.8942652
typography_spectrum: 0.1702509
layout_spectrum: 0.4050179
analytics: {}
cta: {}
