name: Leia of Rage
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#27DA00'
    - '#0275FE'
    - '#FE1EAA'
    - '#7900FD'
  rhythmicContrast: 0.9408602
typography_spectrum: 0.1702509
layout_spectrum: 0.7688172
analytics: {}
cta: {}
