purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.922433
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.288119
typography_spectrum: 0.1702509
layout_spectrum: 0.6666667
cta: {}
analytics: {}
name: Leia of Rage
