name: Leia of Rage
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 1
  brandStrength: 0.6612903
  lightness: 0.922433
  brandColors:
    - '#65CE00'
    - '#FFFFFF'
    - '#01C3FF'
    - '#FF34E8'
    - '#326600'
  rhythmicContrast: 0.288119
typography_spectrum: 0.1702509
cta: {}
analytics: {}
layout_spectrum: 0.6666667
