name: Leia of Rage
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 1
  brandStrength: 0.9336917
  lightness: 0.374552
  brandColors:
    - '#65CE00'
    - '#FFFFFF'
    - '#01C3FF'
    - '#FF34E8'
    - '#326600'
  rhythmicContrast: 0.9408602
typography_spectrum: 0.1702509
layout_spectrum: 1
analytics: {}
cta: {}
